using System;

namespace CLASSES
{
    public class CL_Empresa
    {
        public string emp_nome { get; set; }
        public string emp_ende { get; set; }
        public string emp_comend { get; set; }
        public int emp_nr { get; set; }
        public string emp_bairro { get; set; }
        public string emp_cida { get; set; }
        public string emp_cep { get; set; }
        public string emp_est { get; set; }
        public string emp_fone { get; set; }
        public string emp_dirt { get; set; }
        public string emp_cgc { get; set; }
        public string emp_iscest { get; set; }
        public string emp_ibge { get; set; }
        public string emp_fantas { get; set; }
        public string emp_imunic { get; set; }
        public string emp_email { get; set; }
        public string emp_site { get; set; }
        public string emp_foto { get; set; }
        public double emp_receit { get; set; }
        public int emp_nota { get; set; }
        public string emp_serie { get; set; }
        public int emp_dupl { get; set; }
        public string emp_series { get; set; }
        public int emp_notas { get; set; }
        public string emp_cusipi { get; set; }
        public string emp_cusicm { get; set; }
        public int emp_pont1 { get; set; }
        public int emp_pont2 { get; set; }
        public double emp_cdicm { get; set; }
        public string emp_tipo { get; set; }
        public double emp_cofins { get; set; }
        public double emp_pis { get; set; }
        public double emp_csoc { get; set; }
        public double emp_ir { get; set; }
        public double emp_irven { get; set; }
        public double emp_ircom { get; set; }
        public string emp_tpfed { get; set; }
        public string emp_saida { get; set; }
        public double emp_limest { get; set; }
        public double emp_limfed { get; set; }
        public string emp_tpemis { get; set; }
        public string emp_emissor { get; set; }
        public string emp_filial { get; set; }
        public int emp_linnf { get; set; }
        public string emp_intcon { get; set; }
        public string emp_caljur { get; set; }
        public double emp_perjur { get; set; }
        public double emp_isimp { get; set; }
        public string emp_forger { get; set; }
        public string emp_clipro { get; set; }
        public string emp_forpro { get; set; }
        public string emp_pesnom { get; set; }
        public double emp_vlpis { get; set; }
        public double emp_vlcof { get; set; }
        public double emp_vlsimp { get; set; }
        public double emp_vlcsoc { get; set; }
        public double emp_vlir { get; set; }
        public double emp_vlicm { get; set; }
        public string emp_triger { get; set; }
        public string emp_forcta { get; set; }
        public string emp_serie3 { get; set; }
        public int emp_nota3 { get; set; }
        public string emp_ecf { get; set; }
        public string emp_tprodu { get; set; }
        public int emp_nrconh { get; set; }
        public string emp_ptacup { get; set; }
        public string emp_indice { get; set; }
        public double emp_vlind { get; set; }
        public string emp_tpdupl { get; set; }
        public string emp_digit { get; set; }
        public string emp_tplcli { get; set; }
        public string emp_cadest { get; set; }
        public string emp_tpdigi { get; set; }
        public string emp_calclc { get; set; }
        public string emp_tlcecf { get; set; }
        public string emp_cadcli { get; set; }
        public int emp_prxcli { get; set; }
        public string emp_video { get; set; }
        public string emp_ntacup { get; set; }
        public int emp_prxite { get; set; }
        public string emp_piscof { get; set; }
        public string emp_pasta { get; set; }
        public int emp_lclvct { get; set; }
        public string emp_sped { get; set; }
        public DateTime emp_dataf { get; set; }
        public string emp_tipnfe { get; set; }
        public string emp_nrvias { get; set; }
        public int emp_relrcb { get; set; }
        public string emp_isufra { get; set; }
        public string emp_fax { get; set; }
        public string emp_cnae { get; set; }
        public string emp_pstnfe { get; set; }
        public string emp_crt { get; set; }
        public string emp_usaean { get; set; }
        public string emp_efdpis { get; set; }
        public string emp_tecnic { get; set; }
        public string emp_crea { get; set; }
        public string emp_cpftec { get; set; }
        public string emp_endtec { get; set; }
        public DateTime emp_lmcdta { get; set; }
        public int emp_lmcpag { get; set; }
        public string emp_eminfe { get; set; }
        public string emp_justif { get; set; }
        public string emp_versao { get; set; }
        public int emp_ctacor { get; set; }
        public string emp_dvda1 { get; set; }
        public string emp_dvda2 { get; set; }
        public string emp_dvda3 { get; set; }
        public string emp_dvda4 { get; set; }
        public int emp_diaped { get; set; }
        public double emp_lucro { get; set; }
        public int emp_conhec { get; set; }
        public string emp_sercon { get; set; }
        public double emp_dscven { get; set; }
        public string emp_ecfii { get; set; }
        public string emp_pstcte { get; set; }
        public string emp_pstecf { get; set; }
        public string emp_pstctb { get; set; }
        public string emp_ativid { get; set; }
        public string emp_limcpf { get; set; }
        public string emp_horario { get; set; }
        public int emp_nrmdfe { get; set; }
        public string emp_srmdfe { get; set; }
        public int emp_dealer { get; set; }
        public string emp_tpemnf { get; set; }
        public string emp_tpctas { get; set; }
        public string emp_visnfe { get; set; }
        public string emp_scte2 { get; set; }
        public string emp_ncte2 { get; set; }
        public string emp_android { get; set; }
        public int emp_nrart { get; set; }
        public string emp_token { get; set; }
    }
}