using System;

namespace CLASSES
{
    public class CL_Pedidos
    {
        public DateTime ped_prxvis { get; set; }
        public string ped_assina { get; set; }
        public long ped_idumov { get; set; }
        public int ped_cod { get; set; }
        public string ped_ctrl { get; set; }
        public int ped_codcli { get; set; }
        public DateTime ped_data { get; set; }
        public string est_cod { get; set; }
        public string est_nome { get; set; }
        public string est_nome2 { get; set; }
        public string est_nome3 { get; set; }
        public string est_nome4 { get; set; }
        public string est_tpprod { get; set; }
        public int est_ngrupo { get; set; }
        public int est_nsgrup { get; set; }
        public string est_famil { get; set; }
        public double ped_qtdade { get; set; }
        public double ped_preco { get; set; }
        public double ped_desc { get; set; }
        public double ped_vldesc { get; set; }
        public double ped_qtrec { get; set; }
        public DateTime ped_dtrec { get; set; }
        public int ped_nota { get; set; }
        public int ped_tipo { get; set; }
        public double ped_qtpend { get; set; }
        public int ped_vend { get; set; }
        public int ped_atend { get; set; }
        public string ped_descnt { get; set; }

        public int ped_pz1 { get; set; }
        public DateTime ped_dt1 { get; set; }
        public double ped_vlr1 { get; set; }
        public int ped_pz2 { get; set; }
        public DateTime ped_dt2 { get; set; }
        public double ped_vlr2 { get; set; }
        public int ped_pz3 { get; set; }
        public DateTime ped_dt3 { get; set; }
        public double ped_vlr3 { get; set; }
        public int ped_pz4 { get; set; }
        public DateTime ped_dt4 { get; set; }
        public double ped_vlr4 { get; set; }
        public int ped_pz5 { get; set; }
        public DateTime ped_dt5 { get; set; }
        public double ped_vlr5 { get; set; }
        public int ped_pz6 { get; set; }
        public DateTime ped_dt6 { get; set; }
        public double ped_vlr6 { get; set; }
        public int ped_pz7 { get; set; }
        public DateTime ped_dt7 { get; set; }
        public double ped_vlr7 { get; set; }
        public int ped_pz8 { get; set; }
        public DateTime ped_dt8 { get; set; }
        public double ped_vlr8 { get; set; }
        public int ped_pz9 { get; set; }
        public DateTime ped_dt9 { get; set; }
        public double ped_vlr9 { get; set; }
        public int ped_pz10 { get; set; }
        public DateTime ped_dt10 { get; set; }
        public double ped_vlr10 { get; set; }
        public int ped_pz11 { get; set; }
        public DateTime ped_dt11 { get; set; }
        public double ped_vlr11 { get; set; }
        public int ped_pz12 { get; set; }
        public DateTime ped_dt12 { get; set; }
        public double ped_vlr12 { get; set; }
        public int ped_pz13 { get; set; }
        public DateTime ped_dt13 { get; set; }
        public double ped_vlr13 { get; set; }
        public int ped_pz14 { get; set; }
        public DateTime ped_dt14 { get; set; }
        public double ped_vlr14 { get; set; }
        public int ped_pz15 { get; set; }
        public DateTime ped_dt15 { get; set; }
        public double ped_vlr15 { get; set; }
        public int ped_pz16 { get; set; }
        public DateTime ped_dt16 { get; set; }
        public double ped_vlr16 { get; set; }
        public int ped_pz17 { get; set; }
        public DateTime ped_dt17 { get; set; }
        public double ped_vlr17 { get; set; }
        public int ped_pz18 { get; set; }
        public DateTime ped_dt18 { get; set; }
        public double ped_vlr18 { get; set; }
        public int ped_pz19 { get; set; }
        public DateTime ped_dt19 { get; set; }
        public double ped_vlr19 { get; set; }
        public int ped_pz20 { get; set; }
        public DateTime ped_dt20 { get; set; }
        public double ped_vlr20 { get; set; }
        public DateTime ped_dt21 { get; set; }
        public int ped_pz21 { get; set; }
        public double ped_vlr21 { get; set; }
        public int ped_pz22 { get; set; }
        public DateTime ped_dt22 { get; set; }
        public double ped_vlr22 { get; set; }
        public int ped_pz23 { get; set; }
        public DateTime ped_dt23 { get; set; }
        public double ped_vlr23 { get; set; }
        public int ped_pz24 { get; set; }
        public DateTime ped_dt24 { get; set; }
        public double ped_vlr24 { get; set; }
        public int ped_codtra { get; set; }
        public string ped_transp { get; set; }
        public string trcida { get; set; }
        public string ped_placa1 { get; set; }
        public string ped_obs1 { get; set; }
        public string ped_obs2 { get; set; }
        public string ped_obs3 { get; set; }
        public string ped_obs4 { get; set; }
        public string ped_obs5 { get; set; }
        public DateTime ped_dtsai { get; set; }
        public string ped_hora { get; set; }
        public string ped_cfisc { get; set; }
        public int ped_tribut { get; set; }
        public double ped_comis { get; set; }
        public DateTime ped_inicio { get; set; }
        public DateTime ped_fim { get; set; }
        public double ped_desesp { get; set; }
        public string ped_voltag { get; set; }
        public double ped_frete { get; set; }
        public string ped_famil { get; set; }
        public int ped_tpfret { get; set; }
        public string ped_espec { get; set; }
        public double ped_qtdvol { get; set; }
        public string ped_marca { get; set; }
        public double ped_peso { get; set; }
        public string ped_vdigit { get; set; }
        public string ped_condic { get; set; }
        public string ped_lin1 { get; set; }
        public string ped_lin2 { get; set; }
        public string ped_lin3 { get; set; }
        public string ped_lin4 { get; set; }
        public string ped_lin5 { get; set; }
        public string ped_lin6 { get; set; }
        public string ped_lin7 { get; set; }
        public string ped_lin8 { get; set; }
        public string ped_lin9 { get; set; }
        public string ped_lin10 { get; set; }
        public string ped_lin11 { get; set; }
        public string ped_lin12 { get; set; }
        public string ped_lin13 { get; set; }
        public int ped_ccondic { get; set; }
        public string ped_local { get; set; }
        public double ped_entrad { get; set; }
        public string ped_bloqfi { get; set; }
        public DateTime ped_encer { get; set; }
        public double ped_desace { get; set; }
        public string ped_usudac { get; set; }
        public DateTime ped_movdig { get; set; }
        public string ped_filial { get; set; }
        public DateTime ped_export { get; set; }
        public string ped_cobfre { get; set; }
        public string ped_clinom { get; set; }
        public string ped_cliend { get; set; }
        public string ped_clicid { get; set; }
        public string ped_clicpf { get; set; }
        public string ped_trauf { get; set; }
        public string ped_ufveic { get; set; }
        public double ped_basest { get; set; }
        public double ped_icmst { get; set; }
        public int ped_redesp { get; set; }
        public double ped_vlripi { get; set; }
        public int ped_codend { get; set; }
        public string ped_obped1 { get; set; }
        public string ped_obped2 { get; set; }
        public double ped_qtdfat { get; set; }
        public int ped_dupl { get; set; }
        public string ped_ean { get; set; }
        public string ped_eantri { get; set; }
        public string ped_refer { get; set; }
        public string ped_obsfn1 { get; set; }
        public string ped_obsfn2 { get; set; }
        public string ped_dref { get; set; }
        public string ped_usuar { get; set; }
        public string ped_obssis { get; set; }
        public string ped_unid { get; set; }
        public string ped_rgarma { get; set; }
        public string ped_ngauch { get; set; }
        public string ped_cnpj { get; set; }
        public string ped_iest { get; set; }
        public double ped_vltabe { get; set; }
        public double ped_vlcust { get; set; }
        public double ped_seguro { get; set; }
        public string ped_indpre { get; set; }
        public double ped_pesolq { get; set; }
        public string ped_impres { get; set; }
        public double ped_total { get; set; }
        public double ped_totEst { get; set; }
        public string ped_trcida { get; set; }
    }
}